### PR TITLE
add: xsoar support to splunk TF provider

### PR DESCRIPTION
**Pull request by Xboarder56**
This PR adds action support for the XSOAR action. This will allow users of this terraform provider to configure saved searches with an action to send to XSOAR.

### CODE REVIEW

**Comment by anushjay** [comment]
@Xboarder56 Thanks for your contribution. Can you please look into the test failures and fix any issues/conflicts and update the PR when you have a chance?

**Comment by Xboarder56** [comment]
@anushjay mind kicking off the tests again I resolved the issues? I merged the latest repo sync and ported all the changes over so it should be on the latest code base.

**Comment by anushjay** [comment]
@Xboarder56 I resolved conflicts and kicked off tests on the updated branch. I see a failure and I feel it is related to your changes. Can you please check and let me know or fix if necessary?

`testing.go:684: Step 4 error: Check failed: Check 3/22 error: splunk_saved_searches.test: Attribute 'action_create_xsoar_incident' expected "1", got "0"`

**Comment by Xboarder56** [comment]
@anushjay Still looking into this. I haven't found the reason for the error just yet. Not exactly sure why it's failing as it's being provided 1 in the test config.

**Comment by Xboarder56** [comment]
@anushjay just pushed fixes to resolve the test issues and confirm it works with my local terraform binary when compiled as well. It's good to kick off the test

**Comment by anushjay** [comment]
@Xboarder56 Changes should be available in v1.4.17.

**Pull request merged**
