### PR TITLE
Enahancement of pagerduty integration

### PR DESCRIPTION
**Pull request by mrboso**
Support for defining:
 - pagerduty integration key
 - pagerduty custom details

### CODE REVIEW

**Review by rrossetti-splunk — APPROVED** [review]

**Comment by anushjay** [comment]
Hello @mrboso 
Thanks for your contribution. We are looking to merge this PR to master. Can you please rebase your branch and resubmit so we can run the GitHub actions? We noticed the branch failed linter tests. We will merge after the linter and other tests pass.

**Comment by martin-moravcik-at-ohpen-com** [comment]
Hi @anushjay 
Branch has been rebased. Plz, run the GH actions and merge if they pass. Thanks

**Comment by mrboso** [comment]
Hi @anushjay
Branch has been rebased. Plz, run the GH actions and merge if they pass. Thanks

**Comment by rrossetti-splunk** [comment]
@mrboso It seems that some of the intended functionality has not been implemented here: specifically the action_pagerduty_custom_details field. Would it be possible for you to complete the implementation of this?

As an example, a terraform configuration like this:
`resource "splunk_saved_searches" "search2" {
  name   = "PD Test Alert"
  search = "index=* field=*blah*
  actions = "pagerduty"
  action_pagerduty_integration_url_override = "blah"
  dispatch_earliest_time = "-1d"
  dispatch_latest_time = "now"
...
  disabled = "0"
  action_pagerduty_custom_details = "{Jobs Label: $job.label$}"
  }`

expected outcome would be to see a stanza in savedsearches.conf for PD Test Alert with a value of action.pagerduty.param.custom_details = {Jobs Label: $job.label$}  or the UI equivalent in Splunk Cloud.
What we are seeing is everything being created properly as it did in previous versions, but the new fields for action_pagerduty_custom_details are empty
I have also confirmed this can be done with the savedsearches api endpoint directly and work fine.

**Pull request merged**
