### PR TITLE
Add slack actions

### PR DESCRIPTION
**Pull request by zscholl**
Adds support for configuring slack actions on saved searches.

Addresses #1

### CODE REVIEW

**Comment by anushjay** [comment]
@zscholl Can you also document the resource changes under `docs/resources/saved_searches.md`. Thank you!

**Comment by zscholl** [comment]
Yeah of course! My bad 🙏 

Let me know how it looks @anushjay

**Comment by anushjay** [comment]
@zscholl Can you add a test for the slack actions under `resource_splunk_saved_searches_test`. I tested your changes with the below configuration if you want to use it. Also, users can see how to use the slack alerts this way. 
I believe the `actions` key has to be set for the slack alerts integration to work.
Otherwise the PR LGTM. I can merge it after you add the test. Thanks again!

```
resource "splunk_saved_searches" "slack_alert" {
  name = "Test Slack Alert"
  actions = "slack"
  action_slack_param_attachment = "message"
  action_slack_param_channel = "#channel"
  action_slack_param_message = "error message"
  alert_comparator    = "greater than"
  alert_digest_mode   = true
  alert_expires       = "30d"
  alert_threshold     = "0"
  alert_type          = "number of events"
  cron_schedule       = "*/1 * * * *"
  disabled            = false
  is_scheduled        = true
  is_visible          = true
  realtime_schedule   = true
  search              = "index=main level=error"
}
```

**Comment by zscholl** [comment]
Hmm not sure why the test is failing...I'll look  into this when I have a moment

**Comment by zscholl** [comment]
Figured it out 😅

**Pull request merged**
