### PR TITLE
Adds Cookie handling (fixes #49)

### LINKED ISSUE #49: Authentication issues starting at 1.3.3
I get the following errors when jumping between provider versions 1.3.2 and 1.3.3. It's weird because it only seems to happen when the API is fronted by an AWS ELB. 

Running Splunk 7.2.6

```

$ terraform plan -out=$PLAN_DEV -var-file="terraform/env-dev.tfvars" ./terraform

 Refreshing Terraform state in-memory prior to plan...
 The refreshed state will be used to calculate this plan, but will not be
 persisted to local or remote state storage.
 splunk_saved_searches.AUDIT-0001: Refreshing state... [id=<Redacted>]
 splunk_saved_searches.AUDIT-0004: Refreshing state... [id=<Redacted>]
 splunk_saved_searches.AUDIT-0003: Refreshing state... [id=<Redacted>]
 Error: Http Error: [401] 401 Unauthorized {"messages":[{"type":"WARN","text":"call not properly authenticated"}]}
 Error: Http Error: [401] 401 Unauthorized {"messages":[{"type":"WARN","text":"call not properly authenticated"}]}
 Error: Http Error: [401] 401 Unauthorized {"messages":[{"type":"WARN","text":"call not properly authenticated"}]}
Cleaning up file based variables

```

### PR DESCRIPTION
**Pull request by markdingram**
AWS LB expects cookies to be sent back - see https://docs.aws.amazon.com/elasticloadbalancing/latest/classic/elb-sticky-sessions.html

Didn't think this was worthy of a config option, but let me know.

### CODE REVIEW

**Comment by anushjay** [comment]
@markdingram 
Nice work!
I'm trying to test this out. Do you know if this still requires enabling sticky sessions on the ELB to forward the subsequent requests to the same SH?

**Comment by markdingram** [comment]
I checked & the Terraform for the ELB I've verified this PR against has a lb_cookie_stickiness_policy resource configured. 

I'm not sure what the behaviour would be without that, I'm a consumer of this infra & don't have a sandbox available to test easily.

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_cookie_stickiness_policy

**Comment by markdingram** [comment]
hi @anushjay is there anything I can do to help this move forward?

**Comment by anushjay** [comment]
> hi @anushjay is there anything I can do to help this move forward?

@markdingram Apologies for the delay. I've been trying to test this out but unable to find a setup. I will merge this today and kick off the tagging process as I don't see this break any existing features so you/others can start using it. Thanks for your contribution again!

**Comment by markdingram** [comment]
Thanks, I will give this a try and report back!

**Comment by markdingram** [comment]
> Thanks, I will give this a try and report back!

Up and running successfully in our environment now. Thanks!

**Pull request merged**
